### ISSUE TITLE
Component is unstyled in light mode when there is no `data-theme`

### ISSUE THREAD

**Issue by imtsuki** [vercel-labs/next-tweet#40]
The `theme.css` file includes several CSS variables that are only active when either a `data-theme` attribute is present or the user's `prefers-color-scheme` is set to dark. In the absence of a `data-theme` attribute, the component will appear unstyled in light mode (e.g. lack of borders and colors) but properly styled in dark mode. It would be better to provide styling for the light mode as well, instead of leaving the component unstyled.

<img width="557" alt="light mode" src="https://user-images.githubusercontent.com/8423594/223531208-806e5978-24ee-4509-b697-4b3d97c59f9a.png">

<img width="557" alt="dark mode" src="https://user-images.githubusercontent.com/8423594/223531746-8a247a0a-6911-48b7-8a33-405c2b03aa0b.png">

**Comment by lfades** [comment]
Thank you for the report. I'll fix this asap!
